name: otaldomulaincompetente
description: A starting point for Dart libraries or applications.
version: 2.0.0
homepage: https://github.com/LeonardoBays/otaldomulaincompetente

environment:
  sdk: '>=2.17.5 <4.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
